In [1]:
import numpy as np
arr = np.arange(10)
print(np.sqrt(arr))
print(np.exp(arr))
# np.maximum(x,y)

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


In [3]:
arr = np.random.randn(8)*5
arr

array([-1.86599308, -1.36889688, -1.3504744 , -4.84129171, -3.55984962,
        2.78334167, -5.40947615,  1.46204308])

In [4]:
# modf函数
remainder, whole_part = np.modf(arr)  # 分离小数部分和整数部分
print(remainder)
print(whole_part)

[-0.86599308 -0.36889688 -0.3504744  -0.84129171 -0.55984962  0.78334167
 -0.40947615  0.46204308]
[-1. -1. -1. -4. -3.  2. -5.  1.]


In [5]:
# ufunc 可以接受一个out可选参数,用于存储结果
out = np.zeros_like(arr)
np.add(arr, 1, out=out)
out

array([-0.86599308, -0.36889688, -0.3504744 , -3.84129171, -2.55984962,
        3.78334167, -4.40947615,  2.46204308])

In [ ]:
# 一些ufunc
# 一元:abs fabs sqrt square exp log log10 sign ceil floor rint(四舍五入) modf isnan
# 二元:add subtract multiply divide power maximum minimum mod greater greater_equal less less_equal equal not_equal logical_and logical_or logical_xor