# 4 NumPy基础：数组和向量化计算
## 1.ndarray基本方法

In [136]:
import numpy as np
arr = np.array(5)  #创建0维数组
print(arr)
print(arr.ndim)

5
0


In [137]:
arr = np.array([1,2,3,4,5])  #创建1维数组
print(arr)
print(arr.ndim)

[1 2 3 4 5]
1


In [138]:
arr = np.array([[1,2,3],[4,5,6]])  #创建2维数组
print(arr)
print(arr.ndim)
print(arr.size)
print(arr.T)
print(arr.shape)
print(arr.dtype)

[[1 2 3]
 [4 5 6]]
2
6
[[1 4]
 [2 5]
 [3 6]]
(2, 3)
int64


## 2.numpy创建方法

###   1.基本创建

In [139]:
arr = np.array([1,2,3])

li = [4,5,6]
arr = np.array(li,dtype=np.float64) # 传入列表变量并强制类型转换至浮点数

### 2.复制创建(注意是浅拷贝)

In [140]:
arr1 = np.copy(arr)

### 3.预定义形状

In [141]:
arr = np.zeros((2,3),int)
print(arr)

[[0 0 0]
 [0 0 0]]


In [142]:
arr = np.ones((3,3),int)
print(arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [143]:
arr = np.full((3,4),2025)   #填充
print(arr)

[[2025 2025 2025 2025]
 [2025 2025 2025 2025]
 [2025 2025 2025 2025]]


In [144]:
arr1 = np.zeros_like(arr)
print(arr1)
arr1 = np.ones_like(arr)
print(arr1)
arr1 = np.full_like(arr,2026)
print(arr1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[2026 2026 2026 2026]
 [2026 2026 2026 2026]
 [2026 2026 2026 2026]]


### 4.等差数列

In [145]:
arr = np.arange(1,10,2)   #左闭右开 步长step
print(arr)

[1 3 5 7 9]


### 5.等间隔数列

In [146]:
arr = np.linspace(1,10,5)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


### 6.对数间隔数列

In [147]:
arr = np.logspace(1,5,3,base=2)    #2^1 2^3 2^5
print(arr)

[ 2.  8. 32.]


### 7.特殊矩阵

In [148]:
# 单位矩阵 主对角线全1
arr = np.eye(3,dtype=int)
print(arr)
arr = np.eye(3,4,dtype=int)
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [149]:
# 对角矩阵
arr = np.diag([1,2,3,4])
print(arr)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


### 8.随机数（组）

In [150]:
arr = np.random.rand(3,2)
print(arr)

[[0.3927848  0.83607876]
 [0.33739616 0.64817187]
 [0.36824154 0.95715516]]


In [151]:
arr = np.random.uniform(3,6,(2,3))
print(arr)

[[3.42105234 5.61026178 4.42082414]
 [5.40273226 4.56143244 5.03663859]]


In [152]:
arr = np.random.randint(3,7,(2,3,3))
print(arr)

[[[6 3 4]
  [4 4 6]
  [3 6 5]]

 [[3 6 6]
  [5 6 5]
  [6 3 5]]]


In [153]:
arr = np.random.randn(2,3)   #正态分布
print(arr)

[[-0.39878617 -0.82719653 -0.4157447 ]
 [-0.52451219  0.81310127 -0.22925063]]


In [154]:
np.random.seed(20)   #随机种子 运行结果不会变
arr = np.random.rand(2,3)
print(arr)

[[0.5881308  0.89771373 0.89153073]
 [0.81583748 0.03588959 0.69175758]]


## 3.变量类型

In [155]:
# bool int8 uint8 int16 uint16 int32 uint32 int64 uint64

In [156]:
# float complex 同 int 无 u

## 4.索引与切片

In [157]:
# 一维
np.random.seed(20)
arr = np.random.randint(1,100,10)
print(arr)
print(arr[0])
print(arr[:])   #一行
print(arr[2:5])   #左闭右开 输出第2到第4个（从零开始）
print(arr[slice(2,10,2)])   #start end step
print(arr[ (arr>50) & (arr<90) ])

[91 16 96 29 91 10 21 76 23 72]
91
[91 16 96 29 91 10 21 76 23 72]
[96 29 91]
[96 91 21 23]
[76 72]


In [158]:
# 二维
np.random.seed(20)
arr = np.random.randint(1,50,(4,8))
print(arr)
print(arr[1,3])
print(arr[1,:])   #第一行 :表示所有
print(arr[:,1])
print(arr[1,2:5])   # 2:5同上表示2-4
print(arr[arr>20])   #会返回一维数组
print(arr[2][arr[2]>30])   #第二行中大于50的

[[36 27 16 32 29 27 10 21]
 [12 23  8 35 33 41 22 27]
 [27 20 17 39 39 17 42 38]
 [ 8 38 35  7 27 14 12 26]]
35
[12 23  8 35 33 41 22 27]
[27 23 20 38]
[ 8 35 33]
[36 27 32 29 27 21 23 35 33 41 22 27 27 39 39 42 38 38 35 27 26]
[39 39 42 38]


## 5.运算

In [159]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a//b)
print(a ** 2)
# list相加是拼接 无其他运算
# 二维同理
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a+3)   #全加3
print(a @ b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0 0 0]
[1 4 9]
[4 5 6]
32


## 6.基本计算函数

In [160]:
print(np.sqrt(9))
print(np.sqrt([1,4,9]))
arr = np.array([1,16,81])
print(np.sqrt(arr))

3.0
[1. 2. 3.]
[1. 4. 9.]


In [161]:
print(np.exp(1))

2.718281828459045


In [162]:
print(np.log(2.718281828))

0.9999999998311266


In [163]:
print(np.sin(1))
print(np.cos(1))
print(np.sin(1) ** 2 + np.cos(1) ** 2)
print(np.sin(np.pi/2))

0.8414709848078965
0.5403023058681398
1.0
1.0


In [164]:
arr = np.array([-1,-2,-3,4])
print(np.abs(arr))   #绝对值

[1 2 3 4]


In [165]:
print(np.pow(arr,3))   # a的b次幂

[ -1  -8 -27  64]


In [166]:
print(np.round([3.2,4.5,6.2,4.51]))   #四舍五入

[3. 4. 6. 5.]


In [167]:
print(np.ceil(3.2))    #上取整
print(np.floor(3.2))   #下取整

4.0
3.0


In [168]:
# 检测缺失值NaN
np.isnan([1,2,np.nan,3])

array([False, False,  True, False])

In [169]:
np.random.seed(100)
arr = np.random.randint(1,20,8)
print(arr)
print(np.sum(arr))   # 和
print(np.mean(arr))   # 平均值
print(np.median(arr))   # 中位数
print(np.var(arr))   # 方差
print(np.std(arr))   # 标准差
print(np.max(arr),np.argmax(arr))   # 最大值和最大值索引
print(np.min(arr),np.argmin(arr))   # 最小值和最小值索引
print(np.percentile(arr,70))    # 分位数
print(np.percentile(arr,0))
print(np.cumsum(arr))   # 累积和
print(np.cumprod(arr))   # 累积积

[ 9  4  8 16 17 11  3  3]
71
8.875
8.5
26.859375
5.18260311040697
17 4
3 6
10.799999999999999
3.0
[ 9 13 21 37 54 65 68 71]
[      9      36     288    4608   78336  861696 2585088 7755264]


## 7.基本比较函数

In [170]:
print(np.greater([3,4,5,6,7],4))
print(np.less([3,4,5,6,7],4))
print(np.equal([3,4,5,6,7],4))
print(np.equal([2,3,4],[4,5,6]))

[False False  True  True  True]
[ True False False False False]
[False  True False False False]
[False False False]


In [171]:
print(np.logical_and([1,0],[1,1]))
print(np.logical_or([1,0],[1,1]))
print(np.logical_not([1,0]))

[ True False]
[ True  True]
[False  True]


In [172]:
print(np.any([0,0,0,0]))   # 检查是否至少有一个元素为true
print(np.all([1,1]))   # 检查是否全部元素为true

False
True


In [173]:
# 自定义
# np.where(条件，符合条件，不符合条件))
arr = np.array([1,2,3,4,5])
print(np.where(arr<3,arr,0))
print(np.where(arr>2,1,0))
print(np.where(arr>2,"big","small"))

[1 2 0 0 0]
[0 0 1 1 1]
['small' 'small' 'big' 'big' 'big']


In [174]:
np.random.seed(0)
score = np.random.randint(10,101,20)
print(score)
print(np.where(
    score<60,"不合格",np.where(
        score<80,"良好","优秀"
    )
))

[54 57 74 77 77 19 93 31 46 97 80 98 98 22 68 75 49 97 56 98]
['不合格' '不合格' '良好' '良好' '良好' '不合格' '优秀' '不合格' '不合格' '优秀' '优秀' '优秀' '优秀'
 '不合格' '良好' '良好' '不合格' '优秀' '不合格' '优秀']


In [175]:
# np.select(条件数组,返回结果数组,default=)
print(np.select([score>80,(score>=60)&(score<=80),(score<60)],
                ["优秀","良好","不合格"],
                default="fail"))

['不合格' '不合格' '良好' '良好' '良好' '不合格' '优秀' '不合格' '不合格' '优秀' '良好' '优秀' '优秀'
 '不合格' '良好' '良好' '不合格' '优秀' '不合格' '优秀']


## 8.基本排序函数

In [176]:
print(np.sort(score))   # 不改变score
print(np.argsort(score))
print(score)
score.sort()   # 改变了score
print(score)

[19 22 31 46 49 54 56 57 68 74 75 77 77 80 93 97 97 98 98 98]
[ 5 13  7  8 16  0 18  1 14  2 15  3  4 10  6  9 17 11 12 19]
[54 57 74 77 77 19 93 31 46 97 80 98 98 22 68 75 49 97 56 98]
[19 22 31 46 49 54 56 57 68 74 75 77 77 80 93 97 97 98 98 98]


In [177]:
print(np.unique(score))   # 去重加排序

[19 22 31 46 49 54 56 57 68 74 75 77 80 93 97 98]


In [178]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(np.concatenate([arr1,arr2]))   # 拼接

[1 2 3 4 5 6]


In [179]:
print(np.split(score,4))

[array([19, 22, 31, 46, 49], dtype=int32), array([54, 56, 57, 68, 74], dtype=int32), array([75, 77, 77, 80, 93], dtype=int32), array([97, 97, 98, 98, 98], dtype=int32)]


In [180]:
print(np.split(score,[4,5,15]))

[array([19, 22, 31, 46], dtype=int32), array([49], dtype=int32), array([54, 56, 57, 68, 74, 75, 77, 77, 80, 93], dtype=int32), array([97, 97, 98, 98, 98], dtype=int32)]


In [181]:
print(np.reshape(score,(4,5)))

[[19 22 31 46 49]
 [54 56 57 68 74]
 [75 77 77 80 93]
 [97 97 98 98 98]]
